### ISSUE TITLE
Simulが使用するテストデータをXMLファイルから読み込む

### ISSUE THREAD

**Issue by ej-aoat** [ej-aoat/Kudo#28]
Simulが返すデータに、XMLファイルから取得した値を使用する。
- XMLファイルの配置場所は、固定でよい。
  - XmlSerializer
### ブランチ名
- feature/Simul
### 前提条件
- [ ] DataModelが実装済みであること
### 完了基準
- [x] XMLファイルから値を取得し、オブジェクトが作成できること
  - [x] Category
  - [x] Label
  - [x] Tag
  - [x] Artifact
  - [x] Workspace
- [x] サムネイル情報をXMLファイルから取得する
  - [x] サムネイルとして読み込む画像ファイルを、XMLファイルで指定する

**Comment by ej-aoat** [comment]
まずは、↑にあるDataModelが実装されていること。

**Comment by ej-aoat** [comment]
未実装のDataModelがあるので、目標マイルストーンを変更

**Comment by atachimiko** [comment]
#38
